stages:
  - build
  - deploy

build:
  stage: build
  image: node:20
  script:
    - npm run build
  artifacts:
    paths:
      - dist/
  only:
    - main
    - develop
  before_script:
    - npm install

lint:
  stage: build
  image: node:20
  script:
    - npm run lint
  allow_failure: true
  only:
    - main
    - develop
  before_script:
    - npm install

deploy_production:
  stage: deploy
  image: amazon/aws-cli:latest
  script:
    - aws s3 sync dist/ s3://geotab.link-labs.com --acl public-read --delete
  only:
    - main
  environment:
    name: production
  before_script:
    - echo "Setting up AWS credentials"
    - mkdir -p ~/.aws
    - echo "[default]" > ~/.aws/credentials
    - echo "aws_access_key_id = $AWS_ACCESS_KEY_ID" >> ~/.aws/credentials
    - echo "aws_secret_access_key = $AWS_SECRET_ACCESS_KEY" >> ~/.aws/credentials
    - echo "[default]" > ~/.aws/config
    - echo "region = $AWS_DEFAULT_REGION" >> ~/.aws/config

deploy_develop:
  stage: deploy
  image: amazon/aws-cli:latest
  script:
    - aws s3 sync dist/ s3://dev-geotab.link-labs.com --acl public-read --delete
  only:
    - develop
  environment:
    name: develop
  before_script:
    - echo "Setting up AWS credentials"
    - mkdir -p ~/.aws
    - echo "[default]" > ~/.aws/credentials
    - echo "aws_access_key_id = $AWS_ACCESS_KEY_ID" >> ~/.aws/credentials
    - echo "aws_secret_access_key = $AWS_SECRET_ACCESS_KEY" >> ~/.aws/credentials
    - echo "[default]" > ~/.aws/config
    - echo "region = $AWS_DEFAULT_REGION" >> ~/.aws/config