stages:
  - build
  - verify
  - deploy

variables:
  AWS_S3_BUCKET: ""
  BUILD_ENV: ""

build:
  stage: build
  image: node:20
  script:
    - if [ "$CI_COMMIT_BRANCH" == "main" ]; then export BUILD_ENV=production; else export BUILD_ENV=develop; fi
    - NODE_ENV=$BUILD_ENV npm run build
  artifacts:
    paths:
      - dist/
  only:
    - main
    - develop
  before_script:
    - npm install

lint:
  stage: verify
  image: node:20
  script:
    - npm run lint
  allow_failure: true
  before_script:
    - npm install

audit:
  stage: verify
  image: node:20
  script:
    - npm run audit
  allow_failure: true
  before_script:
    - npm install

deploy:
  stage: deploy
  image: amazon/aws-cli:latest
  script:
    - if [ "$CI_COMMIT_BRANCH" == "main" ]; then export AWS_S3_BUCKET=geotab.link-labs.com; else export AWS_S3_BUCKET=dev-geotab.link-labs.com; fi
    - aws s3 sync dist/ s3://$AWS_S3_BUCKET --acl public-read --delete
  only:
    - main
    - develop
  environment:
    name: production
  before_script:
    - echo "Setting up AWS credentials"
    - mkdir -p ~/.aws
    - echo "[default]" > ~/.aws/credentials
    - echo "aws_access_key_id = $AWS_ACCESS_KEY_ID" >> ~/.aws/credentials
    - echo "aws_secret_access_key = $AWS_SECRET_ACCESS_KEY" >> ~/.aws/credentials
    - echo "[default]" > ~/.aws/config
    - echo "region = $AWS_DEFAULT_REGION" >> ~/.aws/config
  