name: Deploy site to S3

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: "pages"
  cancel-in-progress: false

env:
  BUILD_PATH: "."
  AWS_REGION: "us-east-1"
  S3_BUCKET: "your-s3-bucket-name"

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    name: Build and Deploy to S3
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: npm
          cache-dependency-path: ${{ env.BUILD_PATH }}/package-lock.json
      - name: Install dependencies
        run: npm install
        working-directory: ${{ env.BUILD_PATH }}
      - name: Build with Vite + React
        run: npm run build
        working-directory: ${{ env.BUILD_PATH }}
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      - name: Sync to S3
        run: |
          aws s3 sync ${{ env.BUILD_PATH }}/dist s3://${{ env.S3_BUCKET }}/Airfinder --delete
